[package]
name = "rust-webservice-study"
version = "0.1.0"
authors = ["blueheim"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
