[package]
name = "actix-ws"
version = "0.1.0"
authors = ["blueheim"]
edition = "2021"

[dependencies]
# Workspace
domains = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
# Actix web core
actix-web = "4.3.0"
