ALTER TABLE cats ALTER COLUMN created_on TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE accounts ALTER COLUMN created_on TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE accounts ALTER COLUMN updated_on TYPE TIMESTAMP WITH TIME ZONE;