[package]
name = "common"
version = "0.1.0"
authors = ["XD <blueheim>"]
edition = "2021"


[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
lazy_static = { workspace = true }
validator = { workspace = true }
regex = { workspace = true }