[package]
name = "errors"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { workspace = true }
sqlx = { workspace = true }
actix-web = { workspace = true }
argon2 = { workspace = true }
jsonwebtoken = { workspace = true }