[package]
name = "domains"
version = "0.1.0"
authors = ["XD <blueheim>"]
edition = "2021"

[dependencies]
setup = { workspace = true }
errors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }