# Config file
# For development purpose only

log_level = "info"
database_user = "blueheim"
database_password = "dev"
database_host = "localhost"
database_port = 5432
database_name = "wsstudy"
port = 3000
jwt_secret="jwt_secret_12345"