# Config file
# Used only in development mode

log_level = "info"
database_user = "blueheim"
database_password = "dev"
database_host = "localhost"
database_port = 5432
database_name = "wsstudy"
server_host_ip = "127.0.0.1"
server_port = 3000